version: '3.9'

services:
  nft_media_handler:
    image: ${BLOCKSCOUT_IMAGE:-ghcr.io/blockscout/blockscout@sha256:7659f168e4e2f6b73dd559ae5278fe96ba67bc2905ea01b57a814c68adf5a9dc}
    pull_policy: missing
    restart: always
    stop_grace_period: 5m
    container_name: 'lcbs-nft-media-handler'
    command: sh -c "bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ../envs/common-nft-media-handler.env
    volumes:
      - ./logs/:/app/logs/
